name: check

on:
  issues:
    types: [opened, reopened, edited, labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==1.8.5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          cache: poetry

      - name: Install Python dependencies
        run: poetry install

      - name: Check
        run: poetry run eggtray issue
        env:
          GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
